kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node:22
  commands:
    - corepack enable pnpm
    - pnpm install
    - pnpm test
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack-webhook-url
    channel: drone
    username: Drone (Automated)
    icon_url: https://drone.i258.net/static/media/logo.76c744d4.svg
